version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tg_bot_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: tg_draw_bot
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - prod-network

volumes:
  mysql_data:

networks:
  prod-network:
    driver: bridge
