DROP TABLE IF EXISTS basic_pic;
CREATE TABLE basic_pic
(
    id          INT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    type        VARCHAR(50) NOT NULL COMMENT '基礎圖片類型',
    resource_id INT         NOT NULL COMMENT '對應的資源ID',
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '建立時間',
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間'
);
